project_id = "fzgtckfxntalxrwanhdn"

[functions.send-notification-email]
verify_jwt = false

[functions.moderate-content]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.process-push-queue]
verify_jwt = false
